model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  beta: 10
  loss_type: 'B'

exp_params:
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.0005
  scheduler_gamma: 0.95

trainer_params:
  gpus: [2]
  max_nb_epochs: 50


logging_params:
  save_dir: "logs/"
  name: "BetaVAE_B"
  manual_seed: 1265
