model_params:
  name: 'CategoricalVAE'
  in_channels: 3
  num_classes: 40
  latent_dim: 128
  categorical_dim: 40 # Equal to Num classes
  temperature: 0.5
  anneal_rate: 3e-5
  annela_interval: 100

exp_params:
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50


logging_params:
  save_dir: "logs/"
  name: "CategoricalVAE"
  manual_seed: 1265
