model_params:
  name: 'DIPVAE'
  in_channels: 3
  latent_dim: 128
  lambda_diag: 4.
  lambda_offdiag: 2.


exp_params:
  dataset: celeba
  data_path: "../../shared/momo/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
#  scheduler_gamma: 0.99

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "DIPVAE"
  manual_seed: 1265
