model_params:
  name: 'FactorVAE'
  in_channels: 3
  latent_dim: 128
  gamma: 40

exp_params:
  dataset: celeba
  data_path: "../../shared/Data/"
  submodel: 'discriminator'
  require_secondary_input: True
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  LR_2: 0.005
  scheduler_gamma_2: 0.95

trainer_params:
  gpus: [2]
  max_nb_epochs: 30
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "FactorVAE"
  manual_seed: 1265
