model_params:
  name: 'WAE_MMD'
  in_channels: 3
  latent_dim: 128
  reg_weight: 100
  kernel_type: 'rbf'

exp_params:
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  scheduler_gamma: 0.95

trainer_params:
  gpus: [2]
  max_nb_epochs: 50


logging_params:
  save_dir: "logs/"
  name: "WassersteinVAE"
  manual_seed: 1265




